stages:
  setup:
    cmd:  ipynb-py-convert disease-model.ipynb disease-model.py
    deps:
    - disease-model.ipynb
    outs:
    - disease-model.py  
  train:
    cmd: python disease-model.py
    deps:
    - disease-model.py
    outs:
    - stats.png
    metrics:
    - metrics.json:
        cache: false
