stages:
  setup:
    cmd:  ipynb-py-convert CNN.ipynb CNN.py
    deps:
    - CNN.ipynb
    outs:
    - CNN.py  
  train:
    cmd: python CNN.py
    deps:
    - CNN.py
    outs:
    - cm.png
    metrics:
    - metrics.json:
        cache: false
